pipeline:
  test:
    image: node:8
    commands:
      - npm install
      - npm test
    when:
      branch: master
      event: push

  build:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t asl .
    when:
      branch: master
      event: push

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+asl" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag asl quay.io/ukhomeofficedigital/asl:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/asl:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/asl-deploy-bot
    branch: master
    secrets:
      - drone_token
    params: REPO=${DRONE_REPO},PLUGIN_NUMBER=${DRONE_BUILD_NUMBER},DRONE_TOKEN=${DRONE_TOKEN}
    deploy_to: dev
    when:
      branch: master
      event: push

  dev_deploy:
    image: quay.io/ukhomeofficedigital/kd:v0.5.0
    secrets:
      - kube_server
      - kube_token
    commands:
      - ./deploy/deploy.sh
    when:
      environment: dev
      event: deployment
