module.exports = {
  SET_ESTABLISHMENT: 'SET_ESTABLISHMENT',
  SET_LIST_ITEMS: 'SET_LIST_ITEMS',
  SET_TEXT_FILTER: 'SET_TEXT_FILTER',
  SET_PROFILE: 'SET_PROFILE',
  SET_SCHEMA: 'SET_SCHEMA',
  SET_SORT: 'SET_SORT'
};
